[color]

# Colors for cava
# Mapped to high-contrast M3 tokens

foreground = '{{colors.primary.default.hex}}'

# Gradient colors
gradient = 1
gradient_count = 8
gradient_color_1 = '{{colors.primary.default.hex}}'
gradient_color_2 = '{{colors.primary_fixed.default.hex}}'
gradient_color_3 = '{{colors.secondary.default.hex}}'
gradient_color_4 = '{{colors.secondary_fixed.default.hex}}'
gradient_color_5 = '{{colors.tertiary.default.hex}}'
gradient_color_6 = '{{colors.tertiary_fixed.default.hex}}'
gradient_color_7 = '{{colors.error.default.hex}}'
gradient_color_8 = '{{colors.error_container.default.hex}}'
