#!/usr/bin/env bash

# Find the socket path for Hyprland's socket2
signature="$HYPRLAND_INSTANCE_SIGNATURE"
xdg_runtime="$XDG_RUNTIME_DIR"
socket_path=""

if [ -n "$xdg_runtime" ] && [ -n "$signature" ]; then
    p="$xdg_runtime/hypr/$signature/.socket2.sock"
    if [ -S "$p" ]; then
        socket_path="$p"
    fi
fi

if [ -z "$socket_path" ] && [ -n "$signature" ]; then
    p="/tmp/hypr/$signature/.socket2.sock"
    if [ -S "$p" ]; then
        socket_path="$p"
    fi
fi

if [ -z "$socket_path" ]; then
    socket_path=$(find "${xdg_runtime:-/run/user/$(id -u)}" /tmp -name ".socket2.sock" -print -quit 2>/dev/null)
fi

if [ -z "$socket_path" ]; then
    echo "Error: socket2.sock not found." >&2
    exit 1
fi

# Rules file to modify
rules_file="$HOME/.config/hypr/conf.d/dynamic_flstudio.conf"

update_rules() {
    # Get active clients and filter for FL64.exe
    # Extract workspace names
    fl_workspaces=$(hyprctl clients -j | jq -r '.[] | select(.class == "FL64.exe") | .workspace.name' | sort -u)

    # Generate new content
    new_content=""
    if [ -n "$fl_workspaces" ]; then
        new_content="# Autogenerated by flstudio-workspace.sh"$'\n'
        while read -r ws; do
            if [ -n "$ws" ]; then
                new_content+="workspace = $ws, gapsin:0, gapsout:0"$'\n'
                if [[ "$ws" =~ ^[0-9]+$ ]]; then
                    selector="$ws"
                else
                    selector="name:$ws"
                fi
                new_content+="windowrulev2 = rounding 0, workspace:$selector"$'\n'
                new_content+="windowrulev2 = opacity 1.0 override 1.0 override, workspace:$selector"$'\n'
            fi
        done <<< "$fl_workspaces"
    fi

    # Check if the content changed
    current_content=""
    if [ -f "$rules_file" ]; then
        current_content=$(cat "$rules_file")
    fi

    if [ "$current_content" != "$new_content" ]; then
        mkdir -p "$(dirname "$rules_file")"
        echo -n "$new_content" > "$rules_file"
        hyprctl reload
    fi
}

# Run once initially to handle existing windows
update_rules

# Listen to socket2 events using python3 as a bridge (since socat/nc are missing)
python3 -c '
import socket, sys
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect(sys.argv[1])
while True:
    d = s.recv(4096)
    if not d: break
    sys.stdout.write(d.decode("utf-8", errors="ignore"))
    sys.stdout.flush()
' "$socket_path" | while read -r line; do
    case "$line" in
        openwindow\>\>*|closewindow\>\>*|movewindow\>\>*|movewindowv2\>\>*|changeactiveworkspace\>\>*|workspace\>\>*)
            update_rules
            ;;
    esac
done
