#!/bin/bash

# Define directories
VSCODE_EXT_DIR="$HOME/.vscode/extensions/hyprluna.hyprluna-theme-1.0.2"
ANTIGRAVITY_EXT_DIR="$HOME/.antigravity/extensions/hyprluna.hyprluna-theme-1.0.2"

echo "Creating extension directories..."
mkdir -p "$VSCODE_EXT_DIR/themes"
mkdir -p "$ANTIGRAVITY_EXT_DIR/themes"

# JSON content for package.json
PACKAGE_JSON_CONTENT='{
  "name": "hyprluna-theme",
  "displayName": "HyprLuna Theme",
  "description": "Dynamic Material You theme generated by Matugen",
  "version": "1.0.2",
  "publisher": "hyprluna",
  "engines": {
    "vscode": "^1.50.0"
  },
  "categories": [
    "Themes"
  ],
  "contributes": {
    "themes": [
      {
        "label": "HyprLuna",
        "uiTheme": "vs-dark",
        "path": "./themes/hyprluna.json"
      }
    ]
  }
}'

echo "Writing package.json files..."
echo "$PACKAGE_JSON_CONTENT" > "$VSCODE_EXT_DIR/package.json"
echo "$PACKAGE_JSON_CONTENT" > "$ANTIGRAVITY_EXT_DIR/package.json"

echo "Theme extensions set up successfully!"
echo "Please reload your wallpaper or run your matugen command to generate the colors."
