general {
    lock_cmd = qs -p ~/dotfiles/modified_repos/nandoroid-shell ipc call lock activate
    before_sleep_cmd = qs -p ~/dotfiles/modified_repos/nandoroid-shell ipc call lock abortFingerPam && qs -p ~/dotfiles/modified_repos/nandoroid-shell ipc call lock activate && loginctl lock-session && sleep 1
    after_sleep_cmd = hyprctl dispatch dpms on && ~/.config/hypr/scripts/idle-handler.sh resume-force
}

# 1. Escritorio activo: Atenuar pantalla (5 min)
listener {
    timeout = 300
    on-timeout = ~/.config/hypr/scripts/idle-handler.sh dim
    on-resume = ~/.config/hypr/scripts/idle-handler.sh resume
}

# 2. Escritorio activo: Bloquear sesión (5.5 min)
listener {
    timeout = 330
    on-timeout = loginctl lock-session
}

# 3. Respaldo: Apagar monitor (6 min)
listener {
    timeout = 360
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && ~/.config/hypr/scripts/idle-handler.sh resume-force
}

# 4. Respaldo: Suspensión total (10 min)
listener {
    timeout = 600
    on-timeout = systemctl suspend
}
