# ================================ #
#   Hyprland config file by n3ko   #
# ================================ #
# Wiki ~ https://wiki.hypr.land/Configuring/

# Monitors
source = ~/.config/hypr/conf.d/monitors.conf

# Variables and autostart
source = ~/.config/hypr/conf.d/variables.conf
source = ~/.config/hypr/conf.d/env.conf
source = ~/.config/hypr/conf.d/autostart.conf

# Desing and animations
source = ~/.config/hypr/conf.d/desing.conf
source = ~/.config/hypr/conf.d/animations.conf

# Input and keybinds
source = ~/.config/hypr/conf.d/input.conf
source = ~/.config/hypr/conf.d/keybinds.conf

# Workspaces and windows
source = ~/.config/hypr/conf.d/workspaces.conf

# Plugin
source = ~/.config/hypr/conf.d/hyprgrass.conf