# BEGIN_KITTY_THEME

# COlORS
include current-theme.conf

# OTHER CONFIGS
# Font: JetBrainsMono
font_family JetBrainsMono Nerd Font
font_size 14

# Features
disable_ligatures    no
enable_audio_bell    no
remember_window_size no

# Shell and Cursor
shell                 zsh
shell_integration     no-cursor
cursor_shape          block
url_style             curly
cursor_blink_interval 0

# Padding
window_padding_width  15
window_padding_height 10

# Scroll back up to 3000 lines.
scrollback_lines 3000

# Just a keybind to change font size to your liking, it's CTRL + scroll wheel up or down.
map ctrl+shift+plus  change_font_size all +1.0
map ctrl+shift+minus change_font_size all -1.0

# Keybind for Ctrl+Backspace to delete full word (sends Ctrl+W)
map ctrl+backspace send_text all \x17

# Background and Scroll Bar Opacity
background_opacity             0.85
scrollbar_handle_opacity       0
scrollbar_track_opacity        0
scrollbar_track_handle_opacity 0
confirm_os_window_close        0

# Cursor traile
cursor_trail 3

# Ajusta el decaimiento del rastro (en segundos)
# Un valor más alto hace que el rastro sea más largo
cursor_trail_decay 0.1 0.4

# El rastro solo aparece si el cursor se mueve más de esta distancia (en celdas)
cursor_trail_start_threshold 2

# END_KITTY_THEME