# ===== AUTOSTART =====
# Wiki ~ https://wiki.hypr.land/Useful-Utilities/Systemd-start/

# Scripts y Entorno
exec-once = hyprctl setcursor McMojave Cursors 28

# Servicios de Sistema
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = nm-applet &
exec-once = blueman-applet
exec-once = iio-hyprland
exec-once = ~/.config/hypr/scripts/battery-notifier.sh &

# Interfaz y Estética
exec-once = swww-daemon
exec-once = waybar
exec-once = $notifCenter

# Plugins
exec-once = hyprpm reload
