# ===== HYPRGRASS =====
# WIki ~ https://github.com/horriblename/hyprgrass/blob/main/docs/configuration.md

plugin {
  touch_gestures {
    # The default sensitivity is probably too low on tablet screens,
    # I recommend turning it up to 4.0
    sensitivity = 3.0

    # must be >= 3
    workspace_swipe_fingers = 3

    # in milliseconds
    long_press_delay = 400

    # in pixels, the distance from the edge that is considered an edge
    edge_margin = 10

    # Gestos de deslizamiento (Swipe)
    bindt = , swipe:4:d, killactive
    bindt = , swipe:4:u, fullscreen
    
    # Gestos de borde (Edge swipes)
    bindt = , edge:l:r, exec, $keyboard & $menu
    bindt = , edge:r:l, exec, $browser
    bindt = , edge:d:u, exec, $keyboard 
    bindt = , edge:u:d, exec, $tempCapture
  }
}