# ===== INPUT =====
# https://wiki.hypr.land/Configuring/Variables/#input

# Input config
input {
    kb_layout = es

    follow_mouse = 1
    sensitivity = 0

    touchpad {
        natural_scroll = true
        tap-to-click = true
    }
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace
gesture = 3, vertical, scale: 1, fullscreen