# ===== MONITORS ===== 
# Wiki ~ https://wiki.hypr.land/Configuring/Monitors/

# Monitor 1 (Main laptop screen)
monitor = eDP-1, 1920x1200@60, 1920x0, 1.2

# Other monitors (auto-config)
monitor = , 1920x1080@60, 0x0, 1

# To avoid scale problemas with programs which are not native from Wayland
xwayland {
  force_zero_scaling = true
}
