# ===== DINAMIC VARIABLES =====
# Wiki ~ https://wiki.hypr.land/Configuring/Variables/

# Program variables
$terminal = kitty
$fileManager = kitty -e --hold ~/dotfiles/hyprland/.config/hypr/scripts/yazi.sh
$menu = rofi -show drun -config ~/dotfiles/hyprland/.config/rofi/config.rasi || pkill rofi
$logOut = pkill wlogout || wlogout --buttons-per-row 5
$browser = firefox
$keyboard = pkill -9 wvkbd-mobintl || wvkbd-mobintl -L 300 -bg 11111b -fg-sp 181825 -fg 1e1e2e -press 313244 -press-sp 45475a -alpha 250 -fn 'JetBrainsMono Nerd Font Propo' -text cdd6f4 -text-sp cdd6f4 -R 10
$tempCapture = grim -g "$(slurp)" - | wl-copy # Screenshot to clipboard
$fullScreenshot = hyprshot -m output
$notifCenter = swaync
$noteApp = com.github.flxzt.rnote &
$clipboard = pkill nwg-clipman || nwg-clipman
