# ===== DINAMIC VARIABLES =====
# Wiki ~ https://wiki.hypr.land/Configuring/Variables/

# Program variables
$terminal = kitty
$fileManager = nautilus --new-window
$menu = ~/.config/rofi/launchers/type-1/launcher.sh || pkill rofi
$logOut = pkill wlogout || wlogout --buttons-per-row 5
$browser = firefox
$keyboard = pkill -9 wvkbd-mobintl || wvkbd-mobintl
$tempCapture = grim -g "$(slurp)" - | wl-copy # Screenshot to clipboard
$fullScreenshot = hyprshot -m output
$notifCenter = swaync