# ===== DINAMIC VARIABLES =====
# Wiki ~ https://wiki.hypr.land/Configuring/Variables/

# Program variables
$terminal = kitty
$fileManager = kitty -e --hold ~/dotfiles/hyprland/.config/hypr/scripts/yazi.sh
$browser = helium-browser
$keyboard = pkill -9 wvkbd-mobintl || wvkbd-mobintl -L 300 -bg 11111b -fg-sp 181825 -fg 1e1e2e -press 313244 -press-sp 45475a -alpha 250 -fn 'JetBrainsMono Nerd Font Propo' -text cdd6f4 -text-sp cdd6f4 -R 10
$noteApp = com.github.flxzt.rnote &

# Quickshell variables
$menu = qs -p /home/hypr/dotfiles/modified_repos/nandoroid-shell ipc call launcher toggle
$overview = qs -p /home/hypr/dotfiles/modified_repos/nandoroid-shell ipc call overview toggle
$logOut = qs -p /home/hypr/dotfiles/modified_repos/nandoroid-shell ipc call session toggle
$dashboard = qs -p /home/hypr/dotfiles/modified_repos/nandoroid-shell ipc call dashboard toggle
