# ===== WINDOWS AND WORKSPACES =====
# WIki ~ https://wiki.hypr.land/Configuring/Window-Rules/ for more
# Wiki ~ https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Ignore maximize requests from all apps
windowrule {
    name = suppress-maximize-events
    match:class = .*
    
    suppress_event = maximize
}

# Fix some dragging issues with XWayland
windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# GNOME Calculator
windowrule {
    name = float-calculator
    match:class = org.gnome.Calculator
    float = yes
}

# Waybar Kitty Windows
windowrule {
    name = float-cpufreq
    match:class = local.cpufreq
    size = 1000 800
    float = yes
}
windowrule {
    name = float-bluetui
    match:class = local.bluetui
    size = 1200 800
    float = yes
}
windowrule {
    name = float-impala
    match:class = local.impala
    size = 1200 800
    float = yes
}

